# Generated by Django 5.2.4 on 2025-07-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira')], max_length=3)),
                ('periodo', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde')], max_length=5)),
                ('refeicao', models.CharField(max_length=100)),
                ('bebida', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Refeicao',
        ),
    ]
