# Generated by Django 5.2.4 on 2025-07-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lanche_delete_refeicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardapioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=20)),
                ('manha_segunda', models.CharField(max_length=100)),
                ('manha_terca', models.CharField(max_length=100)),
                ('manha_quarta', models.CharField(max_length=100)),
                ('manha_quinta', models.CharField(max_length=100)),
                ('manha_sexta', models.CharField(max_length=100)),
                ('tarde_segunda', models.CharField(max_length=100)),
                ('tarde_terca', models.CharField(max_length=100)),
                ('tarde_quarta', models.CharField(max_length=100)),
                ('tarde_quinta', models.CharField(max_length=100)),
                ('tarde_sexta', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Lanche',
        ),
    ]
