# Generated by Django 5.2.4 on 2025-08-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='notificacoes',
        ),
        migrations.AddField(
            model_name='perfil',
            name='apelido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_completo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil_fotos/'),
        ),
    ]
